name    'puppet-dropbear'
version '0.0.1'
source  'https://github.com/sbadia/puppet-dropbear'
author  'Sebastien Badia'
license 'GPLv3'
summary 'Puppet Dropbear Module'
description 'Module to install/manage Dropbear SSH server using puppet'
project_page 'https://github.com/sbadia/puppet-dropbear/'
